### ISSUE TITLE
Add synonym cm to centimeter

### ISSUE THREAD

**Issue by cmungall** [bio-ontology-research-group/unit-ontology#28] opened 2020-06-19 03:14 UTC
http://purl.obolibrary.org/obo/UO_0000015 lacks a synonym cm

**Comment by reality** [comment] 2020-11-24 17:57
Closing as er, narrow duplicate of #33. CM is in the OBO file, but was not reflected in the OWL file until now due to that issue.

**Closed by reality** 2020-11-24 17:57 UTC
